ListaDeRamais.E2/Controllers/FunRamaisController.cs
using ListaDeRamais.E2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDeRamais.E2.Controllers
{
    public class FunRamaisController : Controller
    {

        private readonly Banco_ramal2Context _context;

        public FunRamaisController(Banco_ramal2Context context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var FunRamais = await _context.FunRamais
                                            .Include(x => x.CodigoFunFkNavigation)
                                            .Include(n => n.CodigoRamalFkNavigation)
                                            .OrderBy(x => x.CodigoRamalFkNavigation.NumeroRamal)
                                            .ToListAsync();
            return View(FunRamais);
        }

        public IActionResult VisualizarPDF()
        {
            var listapdf = _context.FunRamais
                                            .Include(x => x.CodigoFunFkNavigation)
                                            .Include(n => n.CodigoRamalFkNavigation)
                                            .Include(x=>x.CodigoRamalFkNavigation.CodigoDepFkNavigation)
                                            .OrderBy(x => x.CodigoFunFkNavigation.Nome)
                                            .ToList();

            return new ViewAsPdf("VisualizarPDF", listapdf) { FileName = "dados.pdf" };
        }

        [HttpPost]
        public async Task<IActionResult> Index(string txtProcurar)
        {
            if (!String.IsNullOrEmpty(txtProcurar))
            {

                var listaNome =
                     await _context.FunRamais
                                    .Include(x => x.CodigoFunFkNavigation)
                                    .Include(x => x.CodigoRamalFkNavigation)
                                    .Where(x => x.CodigoFunFkNavigation.Nome.ToUpper().Contains(txtProcurar)
                                           || x.CodigoRamalFkNavigation.NumeroRamal.ToString().Contains(txtProcurar)
                                           || x.CodigoFunFkNavigation.Sobrenome.ToUpper().Contains(txtProcurar))
                                    .ToListAsync();
                return View(listaNome);
            }
            var FunRamais = await _context.FunRamais
                                           .Include(x => x.CodigoFunFkNavigation)
                                           .Include(n => n.CodigoRamalFkNavigation)
                                           .ToListAsync();
                return View(FunRamais);
           

        }


        [HttpGet]
        public IActionResult CriarVinculoRamais()
        {
            var FunRamaisVincular = _context.Funcionarios
                                            .ToList();

             var xlivres = _context.Ramais
                                   .Include(x => x.FunRamais)
                                   .Where(x => x.FunRamais.Count() == 0)
                                   .ToList();

            var viewModel = new VincularViewModel
            {
               CodigoFunFkNavigation = FunRamaisVincular,
               CodigoRamalFkNavigation = xlivres
                                   
            };
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> CriarVinculoRamais(FunRamais funRamais)
        {
            if (ModelState.IsValid)
            {
                _context.Add(funRamais);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else return View(funRamais);
        }

    }
}

ListaDeRamais.E2/Controllers/FuncionarioController.cs
using ListaDeRamais.E2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDeRamais.E2.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly Banco_ramal2Context _context;


        public FuncionarioController(Banco_ramal2Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var contextAux = _context.Funcionarios
                                     .Include(t => t.Telefones)
                                     .Include(x => x.FunRamais);
            return View(await contextAux.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string ProcurarEmFuncionario)
        {
            if (!string.IsNullOrEmpty(ProcurarEmFuncionario))
            {
                var listaNome = _context.Funcionarios
                                         .Include(t => t.Telefones)
                                         .Where(x => x.Nome.ToUpper().Contains(ProcurarEmFuncionario)
                                                  || x.Sobrenome.ToUpper().Contains(ProcurarEmFuncionario)
                                                  || x.Cargo.ToUpper().Contains(ProcurarEmFuncionario)
                                                  || x.Email.ToUpper().Contains(ProcurarEmFuncionario));

                return View(await listaNome.ToListAsync());
            }
            var contextAux = _context.Funcionarios
                                    .Include(t => t.Telefones)
                                    .Include(x => x.FunRamais);
            return View(await contextAux.ToListAsync());
        }



        [HttpGet]

        public IActionResult CriarFuncionario()
        {

            Funcionario funcionario = new Funcionario() { };
            funcionario.Telefones.Add(new Telefone() { });
            funcionario.Telefones.Add(new Telefone() { });

            return View(funcionario);
        }

        [HttpPost]
        public async Task<IActionResult> CriarFuncionario(Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {

                foreach (Telefone telefone in funcionario.Telefones)
                {
                    if (telefone.NumeroTelefone == null)
                        funcionario.Telefones.Remove(telefone);
                }

                _context.Funcionarios.Add(funcionario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }


        [HttpGet]
        public IActionResult AtualizarFuncionario(int id)
        {
            Funcionario funcionario = _context.Funcionarios
                                              .Include(x => x.Telefones)
                                              .Where(x => x.CodigoFunId == id)
                                              .FirstOrDefault();
            return View(funcionario);

        }

        [HttpPost]
        public async Task<IActionResult> AtualizarFuncionario(int? id, Funcionario funcionario)
        {
            if (id != null)
            {
                if (ModelState.IsValid)
                {
                    List<Telefone> listTEL = _context.Telefones
                                                     .Where(x => x.CodigoFunFk == funcionario.CodigoFunId)
                                                     .ToList();
                    _context.Telefones.RemoveRange(listTEL);
                    _context.SaveChanges();

                    _context.Update(funcionario);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                return View(funcionario);
            }
            else return NotFound();

        }

        [HttpGet]
        public IActionResult ExcluirFuncionario(int? id)
        {
            if (id != null)
            {
                Funcionario funcionario = _context.Funcionarios.Find(id);
                return View(funcionario);
            }
            else return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> ExcluirFuncionario(int? id, Funcionario funcionario)
        {
            if (id != null)
            {
                Funcionario funcionariobuscar = _context.Funcionarios.Find(id);

                List<Funcionario> funcionarioIDvinculo = _context.Funcionarios
                                                                 .Include(x => x.FunRamais)
                                                                 .Where(x => x.FunRamais.FirstOrDefault().CodigoFunFk == id)
                                                                 .ToList();

                List<Telefone> listTEL = _context.Telefones
                                                 .Where(x => x.CodigoFunFk == funcionario.CodigoFunId)
                                                 .ToList();
                funcionario = funcionariobuscar;

                if (funcionario.FunRamais == null || funcionario.FunRamais.Count == 0)
                {//remove telefone e funcionario sem vinculo. 
                    _context.Telefones.RemoveRange(listTEL);
                    _context.SaveChanges();

                    _context.Remove(funcionario);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));

                }
                else if (funcionariobuscar.FunRamais != null)
                {//remove vinculo,telefone e funcionario.

                    _context.FunRamais.RemoveRange(funcionariobuscar.FunRamais);
                    _context.Telefones.RemoveRange(listTEL);
                    await _context.SaveChangesAsync();

                    funcionario = funcionariobuscar;

                    _context.Remove(funcionario);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));


            }
            else return NotFound();

        }


    }
}

ListaDeRamais.E2/Controllers/RamaisController.cs
using ListaDeRamais.E2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDeRamais.E2.Controllers
{
    public class RamaisController : Controller
    {
        private readonly Banco_ramal2Context _context;

        public RamaisController(Banco_ramal2Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var contextAux = _context.Ramais.Include(x => x.CodigoDepFkNavigation)
                                            .OrderBy(x => x.NumeroRamal);
            return View(await contextAux.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string ProcurarEmRamais)
        {
            if (!string.IsNullOrEmpty(ProcurarEmRamais))
            {

                var listaNome = await _context.Ramais.Include(x => x.CodigoDepFkNavigation)
                                    .Where(x =>x.NumeroRamal.ToString().Contains(ProcurarEmRamais)
                                            ||x.CodigoDepFkNavigation.Nome.ToUpper().Contains(ProcurarEmRamais))
                                    .ToListAsync();
                return View(listaNome);
            }
            var contextAux = _context.Ramais.Include(x => x.CodigoDepFkNavigation)
                                             .OrderBy(x => x.NumeroRamal);
            return View(await contextAux.ToListAsync());

        }


        [HttpGet]
        public IActionResult CriarRamais()
        {

            var contextAux = _context.Departamentos.ToList();

            var viewModel = new DepartamentoRamaisFormViewModel
            {
                CodigoDepFkNavigation = contextAux,
                Ramais = new List<Ramais>() {  },
            };   
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CriarRamais(Ramais ramal)
        {
            if (ModelState.IsValid)
            {
               var ramalExistente = _context.Ramais
                                            .Where(x=>x.NumeroRamal == ramal.NumeroRamal).ToList();
                var ramaisExistentes = _context.Ramais.ToList();
                
                
                    if (ramalExistente.Count > 0)
                    {
                    return RedirectToAction(nameof(MostrarError));
                }
                    else
                    {
                            _context.Add(ramal);
                            await _context.SaveChangesAsync();
                    }
                    return RedirectToAction(nameof(Index));   
            }
            return NotFound();
        }

        public IActionResult MostrarError()
        {
            var contextAux = _context.Ramais.OrderBy(x => x.NumeroRamal);
            return View(contextAux.ToList()); 
        }

        [HttpGet]
        public IActionResult AtualizarRamais(int? id)
        {
            if (id != null)
            {
                Ramais ramal = _context.Ramais.Find(id);

                var contextAux = _context.Departamentos.ToList();

                var viewModel = new DepartamentoRamaisFormViewModel
                {
                    CodigoDepFkNavigation = contextAux,
                    NumeroRamal = ramal.NumeroRamal,
                    Senha=ramal.Senha,
                    HostIp = ramal.HostIp,
                    CodigoRamalId=ramal.CodigoRamalId
                };
                return View(viewModel);
            }

            else return NotFound();
        }

       

        [HttpPost]
        public async Task<IActionResult> AtualizarRamais(int? id, Ramais ramal)
        {
            if (id != null)
            {
                if (ModelState.IsValid)
                {
                    var ramalRemove = _context.Ramais.Where(x => x.CodigoRamalId == ramal.CodigoRamalId).ToList();
                                      _context.Ramais.RemoveRange(ramalRemove);
                                      _context.Update(ramal);
                                await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else return View(ramal);
            }
            else return NotFound();

        }

        [HttpGet]
        public IActionResult ExcluirRamais(int? id)
        {
            if (id != null )
            {
                Ramais ramal = _context.Ramais.Find(id);
                var contextAux = _context.FunRamais.ToList();
                var contextAux2 = _context.Departamentos.ToList();

                var viewModel = new DepartamentoRamaisFormViewModel
                {
                   CodigoRamalFk = contextAux.FirstOrDefault().CodigoRamalFk,
                   NumeroRamal = ramal.NumeroRamal,
                   HostIp=ramal.HostIp,
                   Senha=ramal.Senha,
                   CodigoDepFkNavigation = contextAux2,
                   Ramais = new List<Ramais>() { ramal },
                };

                return View(viewModel);
            }
            else return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> ExcluirRamais(int? id, Ramais ramal)
        {
            if (id != null  )
            {
                Ramais ramalb = _context.Ramais.Find(id);

                List<Ramais> ramalID = _context.Ramais
                                               .Include(x => x.FunRamais)
                                               .Where(x => x.FunRamais.FirstOrDefault().CodigoRamalFk == id)
                                               .ToList();
                
                if (ramalb.FunRamais == null && ramalID.Count == 0) {//exclui ramal sem vinculo 

                    ramal = ramalb;
                    _context.Remove(ramal);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                } else if (ramalb.FunRamais != null) {// se tiver vinculo, exclui vinculo e depois ramal. 

                    _context.FunRamais
                            .RemoveRange(ramalID.FirstOrDefault().FunRamais);
                    await _context.SaveChangesAsync();

                    ramal = ramalb;

                    _context.Remove(ramal);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            else return NotFound();

        }


    }
}

ListaDeRamais.E2/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "_Layout";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaDeRamais.E2</title>


    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">


    <environment include="Development">
        <link rel="stylesheet" href="~/css/Style.css" />
        <link rel="stylesheet" href="https://bootswatch.com/5/cosmo/bootstrap.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.css" />
        <link rel="stylesheet" herf="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.css" />

        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600,700' rel='stylesheet' type='text/css'>
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.css" rel="stylesheet">
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://bootswatch.com/5/cosmo/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css" />
        <link rel="stylesheet" herf="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>

<body>

    <header>

        <div class="wrapper">
            <div class="cor-bg text-white"
                <nav class="navbar navbar-expand-lg  p-3 mb-2 ">
                    <div class="container-fluid " id="containerNavBar">

                        <a class="navbar-brand" asp-controller="FunRamais" asp-action="Index"></a>
                        <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

                            <span class="navbar-toggler-icon "></span>
                        </button>


                    </div>

                </nav>

              </div>
       </div>
        



    </header>

    <div class="main" id="main">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="sidebar">
        <div class="logoContent">
            <div class="logo">
                <i class='bx bxs-phone'></i>
                <div class="logoName">Lista de Ramais</div>
            </div>
            <!--logo-->
            <i class='bx bx-menu' id="btnMenu"></i>
        </div>
        <!--logoContent-->

        <ul class="nav_list">
            <li>
                <a asp-controller="FunRamais" asp-action="Index">
                    <i class='bx bx-list-ol'></i>
                    <span class="links_name">Lista de Ramais</span> 
                    <!-- <span class="toolipe">Lista de Ramais</span>-->

                </a>
            </li>
            <li>
                <a asp-controller="Departamento" asp-action="Index">
                    <i class='bx bxs-business'></i>
                    <span class="links_name">Ramais por departamento</span>
                    <!-- <span class="toolipe">Ramais por departamento</span>-->
                </a>
            </li>
            <li>
                <a asp-controller="Ramais" asp-action="Index">
                    <i class='bx bx-phone'></i>
                    <span class="links_name">Cadastrar Ramais</span>
                    <!-- <span class="toolipe">Cadastrar Ramais</span>-->

                </a>
            </li>
            <li>
                <a asp-controller="Funcionario" asp-action="Index">
                    <i class='bx bx-user-plus'></i>
                    <span class="links_name">Cadastrar funcionário</span>
                    <!-- <span class="toolipe">Cadastrar funcionário</span>-->
                </a>
            </li>
            <li>
                <a asp-controller="FunRamais" asp-action="CriarVinculoRamais">
                    <i class='bx bx-loader-circle bx-rotate-180'></i>
                    <span class="links_name">Atribuir ramal a funcionário</span>
                    <!-- <span class="toolipe">Atribuir ramal a funcionário</span>-->
                </a>
            </li>
        </ul>

        <div class="profileContent">
            <div class="img-profile">
                <div class="profileDetail">
                    <img class="img-logo" src="" />
                    <div class="nome_job">
                        <div class="name">Lista de Ramais</div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--sidebar-->
    <div class="homeContent">
        <a class="navbar-brand" asp-controller="FunRamais" asp-action="Index">
            <h2>Ramais</h2>
        </a>
    </div>








    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0-beta1/js/bootstrap.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.css"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt-BR.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.js"></script>


        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>